DROP TABLE Individual_cart
DROP TABLE Dish
DROP TABLE Ingredient
DROP TABLE Recipe
DROP TABLE Cart
DROP TABLE [Order]
DROP TABLE Client
DROP TABLE Account
DROP TABLE Employee
DROP TABLE Position
DROP TABLE OrderType
DROP TABLE [Type]